### ISSUE TITLE
Problems with 1) data export and 2) instantaneous velocity

### ISSUE THREAD

**Issue by ShavaniePrashad** [jnirschl/kinesin-3_guedes-dias_2018#1]
Dear Jeff, 

I am just learning to use your script to analyze my data. Using the script on MatLab, I have encountered these two problems frequently as shown in the screenshot below. Is there a way by which these problems can be easily resolved? 

Thank you. 

Best regards, 
Shavanie

![Screen Shot 2020-03-25 at 5 12 47 PM](https://user-images.githubusercontent.com/62673217/77586049-e0f03600-6ebb-11ea-86f2-6c948ceeeefd.png)

**Comment by jnirschl** [comment]
Hi Shavanie, So sorry for the long delay! The error is during creating the Excel COM server. It could be due to a number of factors either in the MATLAB version or OS you are using or settings on your machine. Hopefully, you were able to resolve this on your own or through help on MATLAB Central. If you still need help, please feel free to reach out again.

To best help resolve your issues, you can follow the advice below:
# How to report a bug
When filing an issue, make sure to answer these questions:

    Which operating system and MATLAB version are you using?
    Which version of this project are you using?
    What did you do?
    What did you expect to see?
    What did you see instead?

The best way to get your bug fixed is to provide a test case, and/or steps to reproduce the issue.

**Comment by jnirschl** [comment]
Stale. Feel free to re-open if needed.

**Comment by jnirschl** [comment]
Stale. Feel free to re-open if needed.
